package ProductionControl;


/**
* ProductionControl/_MachineControlStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Interface pour controler UNE machine
public class _MachineControlStub extends org.omg.CORBA.portable.ObjectImpl implements ProductionControl.MachineControl
{


  // Obtenir les informations de MA machine
  public ProductionControl.MachineInfo getMyMachineInfo ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMyMachineInfo", true);
                $in = _invoke ($out);
                ProductionControl.MachineInfo $result = ProductionControl.MachineInfoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMyMachineInfo (        );
            } finally {
                _releaseReply ($in);
            }
  } // getMyMachineInfo


  // Demarrer MA machine
  public ProductionControl.OperationResult startMachine ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startMachine", true);
                $in = _invoke ($out);
                ProductionControl.OperationResult $result = ProductionControl.OperationResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startMachine (        );
            } finally {
                _releaseReply ($in);
            }
  } // startMachine


  // Arreter MA machine
  public ProductionControl.OperationResult stopMachine ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("stopMachine", true);
                $in = _invoke ($out);
                ProductionControl.OperationResult $result = ProductionControl.OperationResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return stopMachine (        );
            } finally {
                _releaseReply ($in);
            }
  } // stopMachine


  // Signaler une panne sur MA machine
  public ProductionControl.OperationResult reportFailure (String description)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("reportFailure", true);
                $out.write_string (description);
                $in = _invoke ($out);
                ProductionControl.OperationResult $result = ProductionControl.OperationResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return reportFailure (description        );
            } finally {
                _releaseReply ($in);
            }
  } // reportFailure


  // Passer MA machine en mode maintenance
  public ProductionControl.OperationResult setMaintenanceMode ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setMaintenanceMode", true);
                $in = _invoke ($out);
                ProductionControl.OperationResult $result = ProductionControl.OperationResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return setMaintenanceMode (        );
            } finally {
                _releaseReply ($in);
            }
  } // setMaintenanceMode


  // Obtenir toutes les machines (lecture seule)
  public ProductionControl.MachineInfo[] getAllMachines ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAllMachines", true);
                $in = _invoke ($out);
                ProductionControl.MachineInfo $result[] = ProductionControl.MachineInfoSequenceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAllMachines (        );
            } finally {
                _releaseReply ($in);
            }
  } // getAllMachines


  // Obtenir les donnees de production globales (lecture seule)
  public ProductionControl.ProductionData getProductionData ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getProductionData", true);
                $in = _invoke ($out);
                ProductionControl.ProductionData $result = ProductionControl.ProductionDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getProductionData (        );
            } finally {
                _releaseReply ($in);
            }
  } // getProductionData

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProductionControl/MachineControl:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "ProductionControl._MachineControlStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MachineControlStub
