package ProductionControl;


/**
* ProductionControl/_ProductionServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Interface du serveur de production
public class _ProductionServerStub extends org.omg.CORBA.portable.ObjectImpl implements ProductionControl.ProductionServer
{


  // Obtenir un controleur pour une machine specifique
  public ProductionControl.MachineControl getMachineControl (int machineId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMachineControl", true);
                $out.write_long (machineId);
                $in = _invoke ($out);
                ProductionControl.MachineControl $result = ProductionControl.MachineControlHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMachineControl (machineId        );
            } finally {
                _releaseReply ($in);
            }
  } // getMachineControl


  // Obtenir les donnees de production
  public ProductionControl.ProductionData getProductionData ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getProductionData", true);
                $in = _invoke ($out);
                ProductionControl.ProductionData $result = ProductionControl.ProductionDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getProductionData (        );
            } finally {
                _releaseReply ($in);
            }
  } // getProductionData

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProductionControl/ProductionServer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "ProductionControl._ProductionServerStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ProductionServerStub
