package ProductionControl;


/**
* ProductionControl/AssemblyStationInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

public final class AssemblyStationInfo implements org.omg.CORBA.portable.IDLEntity
{
  public ProductionControl.StationState state = null;
  public int assembledProducts = (int)0;
  public ProductionControl.StorageZoneInfo storageZones[] = null;

  public AssemblyStationInfo ()
  {
  } // ctor

  public AssemblyStationInfo (ProductionControl.StationState _state, int _assembledProducts, ProductionControl.StorageZoneInfo[] _storageZones)
  {
    state = _state;
    assembledProducts = _assembledProducts;
    storageZones = _storageZones;
  } // ctor

} // class AssemblyStationInfo
