package ProductionControl;


/**
* ProductionControl/AssemblyStationInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

abstract public class AssemblyStationInfoHelper
{
  private static String  _id = "IDL:ProductionControl/AssemblyStationInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.AssemblyStationInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.AssemblyStationInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = ProductionControl.StationStateHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "state",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "assembledProducts",
            _tcOf_members0,
            null);
          _tcOf_members0 = ProductionControl.StorageZoneInfoHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ProductionControl.StorageZoneSequenceHelper.id (), "StorageZoneSequence", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "storageZones",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ProductionControl.AssemblyStationInfoHelper.id (), "AssemblyStationInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.AssemblyStationInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    ProductionControl.AssemblyStationInfo value = new ProductionControl.AssemblyStationInfo ();
    value.state = ProductionControl.StationStateHelper.read (istream);
    value.assembledProducts = istream.read_long ();
    value.storageZones = ProductionControl.StorageZoneSequenceHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.AssemblyStationInfo value)
  {
    ProductionControl.StationStateHelper.write (ostream, value.state);
    ostream.write_long (value.assembledProducts);
    ProductionControl.StorageZoneSequenceHelper.write (ostream, value.storageZones);
  }

}
