package ProductionControl;

/**
* ProductionControl/AssemblyStationInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

public final class AssemblyStationInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.AssemblyStationInfo value = null;

  public AssemblyStationInfoHolder ()
  {
  }

  public AssemblyStationInfoHolder (ProductionControl.AssemblyStationInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.AssemblyStationInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.AssemblyStationInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.AssemblyStationInfoHelper.type ();
  }

}
