package ProductionControl;

/**
* ProductionControl/MachineControlHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Interface pour controler UNE machine
public final class MachineControlHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.MachineControl value = null;

  public MachineControlHolder ()
  {
  }

  public MachineControlHolder (ProductionControl.MachineControl initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.MachineControlHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.MachineControlHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.MachineControlHelper.type ();
  }

}
