package ProductionControl;


/**
* ProductionControl/MachineControlPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Interface pour controler UNE machine
public abstract class MachineControlPOA extends org.omg.PortableServer.Servant
 implements ProductionControl.MachineControlOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getMyMachineInfo", new java.lang.Integer (0));
    _methods.put ("startMachine", new java.lang.Integer (1));
    _methods.put ("stopMachine", new java.lang.Integer (2));
    _methods.put ("reportFailure", new java.lang.Integer (3));
    _methods.put ("setMaintenanceMode", new java.lang.Integer (4));
    _methods.put ("getAllMachines", new java.lang.Integer (5));
    _methods.put ("getProductionData", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Obtenir les informations de MA machine
       case 0:  // ProductionControl/MachineControl/getMyMachineInfo
       {
         ProductionControl.MachineInfo $result = null;
         $result = this.getMyMachineInfo ();
         out = $rh.createReply();
         ProductionControl.MachineInfoHelper.write (out, $result);
         break;
       }


  // Demarrer MA machine
       case 1:  // ProductionControl/MachineControl/startMachine
       {
         ProductionControl.OperationResult $result = null;
         $result = this.startMachine ();
         out = $rh.createReply();
         ProductionControl.OperationResultHelper.write (out, $result);
         break;
       }


  // Arreter MA machine
       case 2:  // ProductionControl/MachineControl/stopMachine
       {
         ProductionControl.OperationResult $result = null;
         $result = this.stopMachine ();
         out = $rh.createReply();
         ProductionControl.OperationResultHelper.write (out, $result);
         break;
       }


  // Signaler une panne sur MA machine
       case 3:  // ProductionControl/MachineControl/reportFailure
       {
         String description = in.read_string ();
         ProductionControl.OperationResult $result = null;
         $result = this.reportFailure (description);
         out = $rh.createReply();
         ProductionControl.OperationResultHelper.write (out, $result);
         break;
       }


  // Passer MA machine en mode maintenance
       case 4:  // ProductionControl/MachineControl/setMaintenanceMode
       {
         ProductionControl.OperationResult $result = null;
         $result = this.setMaintenanceMode ();
         out = $rh.createReply();
         ProductionControl.OperationResultHelper.write (out, $result);
         break;
       }


  // Obtenir toutes les machines (lecture seule)
       case 5:  // ProductionControl/MachineControl/getAllMachines
       {
         ProductionControl.MachineInfo $result[] = null;
         $result = this.getAllMachines ();
         out = $rh.createReply();
         ProductionControl.MachineInfoSequenceHelper.write (out, $result);
         break;
       }


  // Obtenir les donnees de production globales (lecture seule)
       case 6:  // ProductionControl/MachineControl/getProductionData
       {
         ProductionControl.ProductionData $result = null;
         $result = this.getProductionData ();
         out = $rh.createReply();
         ProductionControl.ProductionDataHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProductionControl/MachineControl:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MachineControl _this() 
  {
    return MachineControlHelper.narrow(
    super._this_object());
  }

  public MachineControl _this(org.omg.CORBA.ORB orb) 
  {
    return MachineControlHelper.narrow(
    super._this_object(orb));
  }


} // class MachineControlPOA
