package ProductionControl;


/**
* ProductionControl/MachineControlHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Interface pour controler UNE machine
abstract public class MachineControlHelper
{
  private static String  _id = "IDL:ProductionControl/MachineControl:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.MachineControl that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.MachineControl extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ProductionControl.MachineControlHelper.id (), "MachineControl");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.MachineControl read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MachineControlStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.MachineControl value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ProductionControl.MachineControl narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProductionControl.MachineControl)
      return (ProductionControl.MachineControl)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProductionControl._MachineControlStub stub = new ProductionControl._MachineControlStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ProductionControl.MachineControl unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProductionControl.MachineControl)
      return (ProductionControl.MachineControl)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProductionControl._MachineControlStub stub = new ProductionControl._MachineControlStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
