package ProductionControl;

/**
* ProductionControl/MachineInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

public final class MachineInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.MachineInfo value = null;

  public MachineInfoHolder ()
  {
  }

  public MachineInfoHolder (ProductionControl.MachineInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.MachineInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.MachineInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.MachineInfoHelper.type ();
  }

}
