package ProductionControl;


/**
* ProductionControl/MachineState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Etats des machines
public class MachineState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static ProductionControl.MachineState[] __array = new ProductionControl.MachineState [__size];

  public static final int _STOPPED = 0;
  public static final ProductionControl.MachineState STOPPED = new ProductionControl.MachineState(_STOPPED);
  public static final int _RUNNING = 1;
  public static final ProductionControl.MachineState RUNNING = new ProductionControl.MachineState(_RUNNING);
  public static final int _FAILURE = 2;
  public static final ProductionControl.MachineState FAILURE = new ProductionControl.MachineState(_FAILURE);
  public static final int _MAINTENANCE = 3;
  public static final ProductionControl.MachineState MAINTENANCE = new ProductionControl.MachineState(_MAINTENANCE);

  public int value ()
  {
    return __value;
  }

  public static ProductionControl.MachineState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected MachineState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class MachineState
