package ProductionControl;


/**
* ProductionControl/MachineTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Types de machines
abstract public class MachineTypeHelper
{
  private static String  _id = "IDL:ProductionControl/MachineType:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.MachineType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.MachineType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (ProductionControl.MachineTypeHelper.id (), "MachineType", new String[] { "TYPE_A", "TYPE_B", "TYPE_C", "TYPE_D"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.MachineType read (org.omg.CORBA.portable.InputStream istream)
  {
    return ProductionControl.MachineType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.MachineType value)
  {
    ostream.write_long (value.value ());
  }

}
