package ProductionControl;


/**
* ProductionControl/MachineControl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Interface pour controler UNE machine
public interface MachineControl extends MachineControlOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MachineControl
