package ProductionControl;

/**
* ProductionControl/MachineStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Etats des machines
public final class MachineStateHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.MachineState value = null;

  public MachineStateHolder ()
  {
  }

  public MachineStateHolder (ProductionControl.MachineState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.MachineStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.MachineStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.MachineStateHelper.type ();
  }

}
