package ProductionControl;


/**
* ProductionControl/MachineType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Types de machines
public class MachineType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static ProductionControl.MachineType[] __array = new ProductionControl.MachineType [__size];

  public static final int _TYPE_A = 0;
  public static final ProductionControl.MachineType TYPE_A = new ProductionControl.MachineType(_TYPE_A);
  public static final int _TYPE_B = 1;
  public static final ProductionControl.MachineType TYPE_B = new ProductionControl.MachineType(_TYPE_B);
  public static final int _TYPE_C = 2;
  public static final ProductionControl.MachineType TYPE_C = new ProductionControl.MachineType(_TYPE_C);
  public static final int _TYPE_D = 3;
  public static final ProductionControl.MachineType TYPE_D = new ProductionControl.MachineType(_TYPE_D);

  public int value ()
  {
    return __value;
  }

  public static ProductionControl.MachineType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected MachineType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class MachineType
