package ProductionControl;


/**
* ProductionControl/MachineStateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Etats des machines
abstract public class MachineStateHelper
{
  private static String  _id = "IDL:ProductionControl/MachineState:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.MachineState that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.MachineState extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (ProductionControl.MachineStateHelper.id (), "MachineState", new String[] { "STOPPED", "RUNNING", "FAILURE", "MAINTENANCE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.MachineState read (org.omg.CORBA.portable.InputStream istream)
  {
    return ProductionControl.MachineState.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.MachineState value)
  {
    ostream.write_long (value.value ());
  }

}
