package ProductionControl;


/**
* ProductionControl/MachineInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/

public final class MachineInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;
  public ProductionControl.MachineType type = null;
  public ProductionControl.MachineState state = null;
  public ProductionControl.PartType currentPart = null;
  public int productionCount = (int)0;

  public MachineInfo ()
  {
  } // ctor

  public MachineInfo (int _id, String _name, ProductionControl.MachineType _type, ProductionControl.MachineState _state, ProductionControl.PartType _currentPart, int _productionCount)
  {
    id = _id;
    name = _name;
    type = _type;
    state = _state;
    currentPart = _currentPart;
    productionCount = _productionCount;
  } // ctor

} // class MachineInfo
