package ProductionControl;


/**
* ProductionControl/MachineControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Interface pour controler UNE machine
public interface MachineControlOperations 
{

  // Obtenir les informations de MA machine
  ProductionControl.MachineInfo getMyMachineInfo ();

  // Demarrer MA machine
  ProductionControl.OperationResult startMachine ();

  // Arreter MA machine
  ProductionControl.OperationResult stopMachine ();

  // Signaler une panne sur MA machine
  ProductionControl.OperationResult reportFailure (String description);

  // Passer MA machine en mode maintenance
  ProductionControl.OperationResult setMaintenanceMode ();

  // Obtenir toutes les machines (lecture seule)
  ProductionControl.MachineInfo[] getAllMachines ();

  // Obtenir les donnees de production globales (lecture seule)
  ProductionControl.ProductionData getProductionData ();
} // interface MachineControlOperations
