package ProductionControl;


/**
* ProductionControl/MachineInfoSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

public final class MachineInfoSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.MachineInfo value[] = null;

  public MachineInfoSequenceHolder ()
  {
  }

  public MachineInfoSequenceHolder (ProductionControl.MachineInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.MachineInfoSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.MachineInfoSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.MachineInfoSequenceHelper.type ();
  }

}
