package ProductionControl;

/**
* ProductionControl/MachineTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Types de machines
public final class MachineTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.MachineType value = null;

  public MachineTypeHolder ()
  {
  }

  public MachineTypeHolder (ProductionControl.MachineType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.MachineTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.MachineTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.MachineTypeHelper.type ();
  }

}
