package ProductionControl;


/**
* ProductionControl/OperationResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

public final class OperationResult implements org.omg.CORBA.portable.IDLEntity
{
  public boolean success = false;
  public String message = null;

  public OperationResult ()
  {
  } // ctor

  public OperationResult (boolean _success, String _message)
  {
    success = _success;
    message = _message;
  } // ctor

} // class OperationResult
