package ProductionControl;

/**
* ProductionControl/OperationResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

public final class OperationResultHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.OperationResult value = null;

  public OperationResultHolder ()
  {
  }

  public OperationResultHolder (ProductionControl.OperationResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.OperationResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.OperationResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.OperationResultHelper.type ();
  }

}
