package ProductionControl;


/**
* ProductionControl/PartType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Types de pieces
public class PartType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static ProductionControl.PartType[] __array = new ProductionControl.PartType [__size];

  public static final int _PART_TYPE_A = 0;
  public static final ProductionControl.PartType PART_TYPE_A = new ProductionControl.PartType(_PART_TYPE_A);
  public static final int _PART_TYPE_B = 1;
  public static final ProductionControl.PartType PART_TYPE_B = new ProductionControl.PartType(_PART_TYPE_B);
  public static final int _PART_TYPE_C = 2;
  public static final ProductionControl.PartType PART_TYPE_C = new ProductionControl.PartType(_PART_TYPE_C);
  public static final int _PART_TYPE_D = 3;
  public static final ProductionControl.PartType PART_TYPE_D = new ProductionControl.PartType(_PART_TYPE_D);

  public int value ()
  {
    return __value;
  }

  public static ProductionControl.PartType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected PartType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class PartType
