package ProductionControl;

/**
* ProductionControl/PartTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Types de pieces
public final class PartTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.PartType value = null;

  public PartTypeHolder ()
  {
  }

  public PartTypeHolder (ProductionControl.PartType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.PartTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.PartTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.PartTypeHelper.type ();
  }

}
