package ProductionControl;


/**
* ProductionControl/PartTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Types de pieces
abstract public class PartTypeHelper
{
  private static String  _id = "IDL:ProductionControl/PartType:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.PartType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.PartType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (ProductionControl.PartTypeHelper.id (), "PartType", new String[] { "PART_TYPE_A", "PART_TYPE_B", "PART_TYPE_C", "PART_TYPE_D"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.PartType read (org.omg.CORBA.portable.InputStream istream)
  {
    return ProductionControl.PartType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.PartType value)
  {
    ostream.write_long (value.value ());
  }

}
