package ProductionControl;

/**
* ProductionControl/ProductionDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

public final class ProductionDataHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.ProductionData value = null;

  public ProductionDataHolder ()
  {
  }

  public ProductionDataHolder (ProductionControl.ProductionData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.ProductionDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.ProductionDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.ProductionDataHelper.type ();
  }

}
