package ProductionControl;


/**
* ProductionControl/ProductionDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

abstract public class ProductionDataHelper
{
  private static String  _id = "IDL:ProductionControl/ProductionData:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.ProductionData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.ProductionData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = ProductionControl.MachineInfoHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ProductionControl.MachineInfoSequenceHelper.id (), "MachineInfoSequence", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "machines",
            _tcOf_members0,
            null);
          _tcOf_members0 = ProductionControl.AssemblyStationInfoHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "assemblyStation",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ProductionControl.ProductionDataHelper.id (), "ProductionData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.ProductionData read (org.omg.CORBA.portable.InputStream istream)
  {
    ProductionControl.ProductionData value = new ProductionControl.ProductionData ();
    value.machines = ProductionControl.MachineInfoSequenceHelper.read (istream);
    value.assemblyStation = ProductionControl.AssemblyStationInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.ProductionData value)
  {
    ProductionControl.MachineInfoSequenceHelper.write (ostream, value.machines);
    ProductionControl.AssemblyStationInfoHelper.write (ostream, value.assemblyStation);
  }

}
