package ProductionControl;


/**
* ProductionControl/ProductionServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Interface du serveur de production
abstract public class ProductionServerHelper
{
  private static String  _id = "IDL:ProductionControl/ProductionServer:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.ProductionServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.ProductionServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ProductionControl.ProductionServerHelper.id (), "ProductionServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.ProductionServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ProductionServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.ProductionServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ProductionControl.ProductionServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProductionControl.ProductionServer)
      return (ProductionControl.ProductionServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProductionControl._ProductionServerStub stub = new ProductionControl._ProductionServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ProductionControl.ProductionServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProductionControl.ProductionServer)
      return (ProductionControl.ProductionServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProductionControl._ProductionServerStub stub = new ProductionControl._ProductionServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
