package ProductionControl;


/**
* ProductionControl/ProductionServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Interface du serveur de production
public abstract class ProductionServerPOA extends org.omg.PortableServer.Servant
 implements ProductionControl.ProductionServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getMachineControl", new java.lang.Integer (0));
    _methods.put ("getProductionData", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Obtenir un controleur pour une machine specifique
       case 0:  // ProductionControl/ProductionServer/getMachineControl
       {
         int machineId = in.read_long ();
         ProductionControl.MachineControl $result = null;
         $result = this.getMachineControl (machineId);
         out = $rh.createReply();
         ProductionControl.MachineControlHelper.write (out, $result);
         break;
       }


  // Obtenir les donnees de production
       case 1:  // ProductionControl/ProductionServer/getProductionData
       {
         ProductionControl.ProductionData $result = null;
         $result = this.getProductionData ();
         out = $rh.createReply();
         ProductionControl.ProductionDataHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProductionControl/ProductionServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ProductionServer _this() 
  {
    return ProductionServerHelper.narrow(
    super._this_object());
  }

  public ProductionServer _this(org.omg.CORBA.ORB orb) 
  {
    return ProductionServerHelper.narrow(
    super._this_object(orb));
  }


} // class ProductionServerPOA
