package ProductionControl;


/**
* ProductionControl/ProductionData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/

public final class ProductionData implements org.omg.CORBA.portable.IDLEntity
{
  public ProductionControl.MachineInfo machines[] = null;
  public ProductionControl.AssemblyStationInfo assemblyStation = null;

  public ProductionData ()
  {
  } // ctor

  public ProductionData (ProductionControl.MachineInfo[] _machines, ProductionControl.AssemblyStationInfo _assemblyStation)
  {
    machines = _machines;
    assemblyStation = _assemblyStation;
  } // ctor

} // class ProductionData
