package ProductionControl;

/**
* ProductionControl/ProductionServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Interface du serveur de production
public final class ProductionServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.ProductionServer value = null;

  public ProductionServerHolder ()
  {
  }

  public ProductionServerHolder (ProductionControl.ProductionServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.ProductionServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.ProductionServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.ProductionServerHelper.type ();
  }

}
