package ProductionControl;


/**
* ProductionControl/ProductionServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Interface du serveur de production
public interface ProductionServerOperations 
{

  // Obtenir un controleur pour une machine specifique
  ProductionControl.MachineControl getMachineControl (int machineId);

  // Obtenir les donnees de production
  ProductionControl.ProductionData getProductionData ();
} // interface ProductionServerOperations
