package ProductionControl;


/**
* ProductionControl/ProductionServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Interface du serveur de production
public interface ProductionServer extends ProductionServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProductionServer
