package ProductionControl;


/**
* ProductionControl/StationState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Etats de la station d'assemblage
public class StationState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static ProductionControl.StationState[] __array = new ProductionControl.StationState [__size];

  public static final int _IDLE = 0;
  public static final ProductionControl.StationState IDLE = new ProductionControl.StationState(_IDLE);
  public static final int _ASSEMBLING = 1;
  public static final ProductionControl.StationState ASSEMBLING = new ProductionControl.StationState(_ASSEMBLING);
  public static final int _WAITING_PARTS = 2;
  public static final ProductionControl.StationState WAITING_PARTS = new ProductionControl.StationState(_WAITING_PARTS);

  public int value ()
  {
    return __value;
  }

  public static ProductionControl.StationState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected StationState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class StationState
