package ProductionControl;

/**
* ProductionControl/StationStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/


// Etats de la station d'assemblage
public final class StationStateHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.StationState value = null;

  public StationStateHolder ()
  {
  }

  public StationStateHolder (ProductionControl.StationState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.StationStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.StationStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.StationStateHelper.type ();
  }

}
