package ProductionControl;


/**
* ProductionControl/StorageZoneInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/

public final class StorageZoneInfo implements org.omg.CORBA.portable.IDLEntity
{
  public ProductionControl.PartType partType = null;
  public int currentQuantity = (int)0;
  public int maxCapacity = (int)0;

  public StorageZoneInfo ()
  {
  } // ctor

  public StorageZoneInfo (ProductionControl.PartType _partType, int _currentQuantity, int _maxCapacity)
  {
    partType = _partType;
    currentQuantity = _currentQuantity;
    maxCapacity = _maxCapacity;
  } // ctor

} // class StorageZoneInfo
