package ProductionControl;


/**
* ProductionControl/StorageZoneInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:32:41 PM WAT
*/

abstract public class StorageZoneInfoHelper
{
  private static String  _id = "IDL:ProductionControl/StorageZoneInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.StorageZoneInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.StorageZoneInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = ProductionControl.PartTypeHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "partType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "currentQuantity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "maxCapacity",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ProductionControl.StorageZoneInfoHelper.id (), "StorageZoneInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.StorageZoneInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    ProductionControl.StorageZoneInfo value = new ProductionControl.StorageZoneInfo ();
    value.partType = ProductionControl.PartTypeHelper.read (istream);
    value.currentQuantity = istream.read_long ();
    value.maxCapacity = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.StorageZoneInfo value)
  {
    ProductionControl.PartTypeHelper.write (ostream, value.partType);
    ostream.write_long (value.currentQuantity);
    ostream.write_long (value.maxCapacity);
  }

}
