package ProductionControl;

/**
* ProductionControl/StorageZoneInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/

public final class StorageZoneInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.StorageZoneInfo value = null;

  public StorageZoneInfoHolder ()
  {
  }

  public StorageZoneInfoHolder (ProductionControl.StorageZoneInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.StorageZoneInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.StorageZoneInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.StorageZoneInfoHelper.type ();
  }

}
