package ProductionControl;


/**
* ProductionControl/StorageZoneSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Sequences (typedef requis)
public final class StorageZoneSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControl.StorageZoneInfo value[] = null;

  public StorageZoneSequenceHolder ()
  {
  }

  public StorageZoneSequenceHolder (ProductionControl.StorageZoneInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControl.StorageZoneSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControl.StorageZoneSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControl.StorageZoneSequenceHelper.type ();
  }

}
