package ProductionControl;


/**
* ProductionControl/StorageZoneSequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProductionControl.idl
* Wednesday, December 10, 2025 4:31:38 PM WAT
*/


// Sequences (typedef requis)
abstract public class StorageZoneSequenceHelper
{
  private static String  _id = "IDL:ProductionControl/StorageZoneSequence:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControl.StorageZoneInfo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControl.StorageZoneInfo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ProductionControl.StorageZoneInfoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ProductionControl.StorageZoneSequenceHelper.id (), "StorageZoneSequence", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControl.StorageZoneInfo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ProductionControl.StorageZoneInfo value[] = null;
    int _len0 = istream.read_long ();
    value = new ProductionControl.StorageZoneInfo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ProductionControl.StorageZoneInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControl.StorageZoneInfo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ProductionControl.StorageZoneInfoHelper.write (ostream, value[_i0]);
  }

}
